# main configuration file for mkdocs generation of the Yasumi website

# project information
site_author: Sacha Telgenhof
site_description: The easy PHP Library for calculating holidays
site_name: Yasumi
site_url: https://azuyalabs.github.io/yasumi-docs

# repository
repo_url: https://github.com/azuyalabs/yasumi
repo_name: azuyalabs/yasumi

edit_uri: "https://github.com/azuyalabs/yasumi-docs/blob/main/"
use_directory_urls: False

copyright: |
  Copyright &copy; 2015 - 2024 <a href="https://github.com/stelgenhof" target="_blank" rel="noopener">Sacha Telgenhof</a>

# configuration
theme:
  name: material
  palette:
    scheme: yasumi
  #logo: assets/img/yasumi_logo.svg
  font:
    text: Inter
  favicon: assets/img/favicon.ico
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow

# plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
  - inline-svg

# extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

extra_css:
  - assets/css/yasumi.css

# navigation tree
nav:
  - Home: "about.md"
  - Documentation:
      - Getting started: "getting-started.md"
      - Holiday Providers:
          - Overview: "providers/providers.md"
          - Argentina: "providers/ar.md"
          - Australia: "providers/au.md"
          - Austria: "providers/at.md"
          - Belgium: "providers/be.md"
          - Bosnia &amp; Herzegovina: "providers/ba.md"
          - Brazil: "providers/br.md"
          - Canada: "providers/ca.md"
          - Croatia: "providers/hr.md"
          - Czech Republic: "providers/cz.md"
          - Denmark: "providers/dk.md"
          - Estonia: "providers/ee.md"
          - Finland: "providers/fi.md"
          - France: "providers/fr.md"
          - Georgia: "providers/ge.md"
          - Germany: "providers/de.md"
          - Greece: "providers/gr.md"
          - Hungary: "providers/hu.md"
          - Iran: "providers/ir.md"
          - Ireland: "providers/ie.md"
          - Italy: "providers/it.md"
          - Japan: "providers/jp.md"
          - Latvia: "providers/lv.md"
          - Lithuania: "providers/lt.md"
          - Luxembourg: "providers/lu.md"
          - Mexico: "providers/mx.md"
          - Netherlands: "providers/nl.md"
          - New Zealand: "providers/nz.md"
          - Norway: "providers/no.md"
          - Poland: "providers/pl.md"
          - Portugal: "providers/pt.md"
          - Romania: "providers/ro.md"
          - Russia: "providers/ru.md"
          - Slovakia: "providers/sk.md"
          - South Africa: "providers/za.md"
          - South Korea: "providers/kr.md"
          - Spain: "providers/es.md"
          - Sweden: "providers/se.md"
          - Switzerland: "providers/ch.md"
          - Türkiye: "providers/tr.md"
          - United States: "providers/us.md"
          - Ukraine: "providers/ua.md"
          - United Kingdom: "providers/gb.md"
      - Filters: "filters.md"
      - Cookbook:
          - Basic: "recipes/basic.md"
          - Date Range: "recipes/between_filter.md"
          - Custom Provider: "recipes/custom_provider.md"
          - Filter Holidays: "recipes/filters.md"
      - Security and Support: "security.md"
  - Developers:
      - Developers: "developers/index.md"
      - Contributing: "developers/contributing.md"
      - Testing: "developers/testing.md"
  - Releases:
      - Releases: "releases/index.md"
      - 2.7.0: "releases/2.7.0.md"
      - 2.6.0: "releases/2.6.0.md"
      - 2.5.0: "releases/2.5.0.md"
      - 2.4.0: "releases/2.4.0.md"
      - 2.3.0: "releases/2.3.0.md"
      - 2.2.0: "releases/2.2.0.md"
      - 2.1.0: "releases/2.1.0.md"
      - 2.0.0: "releases/2.0.0.md"
      - 1.8.1: "releases/1.8.1.md"
      - 1.8.0: "releases/1.8.0.md"
      - 1.7.0: "releases/1.7.0.md"
      - 1.6.1: "releases/1.6.1.md"
      - 1.6.0: "releases/1.6.0.md"
      - 1.5.0: "releases/1.5.0.md"
      - 1.4.0: "releases/1.4.0.md"
      - 1.3.0: "releases/1.3.0.md"
      - 1.2.0: "releases/1.2.0.md"
      - 1.1.0: "releases/1.1.0.md"
      - 1.0.0: "releases/1.0.0.md"
  